export const StaticData = {
    Subhead:"Find Your Nearest Restaurant",
    Searchbox:"TO Find",
    Meta_title:" Matalan Demo Store - Online Clothes Store",
    Meta_description:"Visit Matalan Demo Store | Matalan is your local great value family retailer shop. Find latest seasonal looks for Women, Men and kids, plus a huge range of homeware.",
    locator_breadcrumb:"Store Locator",
    FindLocationtext:"Hippopotamus restaurants nearby:",
    Usemylocation:"Use my location",
    Search:"Search",
    Brandname:"MGM Timber",
    miles:"KM",
    tempClosed:"Temporarily Closed",
    StoreDetailbtn:"View Store Detail",
    Storehighlight:"Store Highlights",
    Days:"Days",
    Hours:"Hours",
    Minutes:"Minutes",
    Seconds:"Seconds",
    FAQheading:"How can we help ?",
    getDirection:"Directions",
    AllRegion:"All Regions of",
    NearStoretext:"NEARBY LOCATIONS",
    AllLocationtext:"View All Location",
    PagenotFound:"404 - Page Not Found",
    cantfind_page:"We're really sorry, we can't find the page you're looking for",
    Youcouldtry:"You could try",
    Previuspage:"Going back to the previous page",
    homePage:"Going back to the homepage",
    StoreFinder:"Store Finder",
    FAQs:"FAQs",
    DownloadApp:"Download Our App",
    cookie:"cookies policy",
    Closed:"Closed",
    DayofWeek:"Day of the Week",
    Reopenmessage:"Message - The store is temporarily closed. It will reopen at",
    Address:"Address",
    Telephone:"Telephone",
    Holdiay:"Holdiday Hours",
    }